### ISSUE TITLE
[FEATURE] terragrunt support

### ISSUE THREAD

**Issue by ghulteen** [patrickchugh/terravision#114]
In our env we use terragrunt. so I created symlink "localterraform -> terragrunt" and updated the modules/ftwrapper.py which got me closer but it seems that terravision now cannot find the .tf files in the local directory. My guess right now is that it doesn't understand the module config. Are there any  plan to test/add terragrunt support?

**Comment by patrickchugh** [comment]
Hi @ghulteen could you share an example repo using Terragrunt and how would you expect it to work?

**Comment by patrickchugh** [comment]
@lgg42 any luck trying this ?

**Comment by lgg42** [comment]
Hi! I just tried out the single unit scenario **rds/shared**. ⚠️ These past days I have upgraded my terraform binary.

**terravision 0.32.0
terragrunt  0.94.0
terraform 1.14.8**

I do `rm -rf .terragrunt-cache*` first

then `terragrunt init`, then `terragrunt plan`, everything ok.

Then I execute `terravision draw --debug --source .`, this is the output:

```
$ terravision draw --debug --source .


 _____                          _     _             
/__   \___ _ __ _ __ __ ___   _(_)___(_) ___  _ __  
  / /\/ _ \ '__| '__/ _` \ \ / / / __| |/ _ \| '_ \ 
 / / |  __/ |  | | | (_| |\ V /| \__ \ | (_) | | | |
 \/   \___|_|  |_|  \__,_| \_/ |_|___/_|\___/|_| |_|



Preflight check..
  dot command detected: /usr/bin/dot
  gvpr command detected: /usr/bin/gvpr
  git command detected: /usr/bin/git
  terraform command detected: /usr/local/bin/terraform
  terraform version detected: Terraform v1.14.8



Terragrunt detected (single-module)


Running Terragrunt Init..

╷
│ Error: Backend initialization required, please run "terraform init"
│ 
│ Reason: Initial configuration of the requested backend "s3"
│ 
│ The "backend" is the interface that Terraform uses to store state,
│ perform operations, etc. If this message is showing up, it means that the
│ Terraform configuration you're using is using a custom configuration for
│ the Terraform backend.
│ 
│ Changes to backend configurations require reinitialization. This allows
│ Terraform to set up the new configuration, copy existing state, etc. Please
│ run
│ "terraform init" with either the "-reconfigure" or "-migrate-state" flags
│ to
│ use the current configuration.
│ 
│ If the change reason above is incorrect, please verify your configuration
│ hasn't changed and try again. At this point, no changes to your existing
│ configuration or state have been made.
╵
╷
│ Error: Backend initialization required, please run "terraform init"
│ 
│ Reason: Initial configuration of the requested backend "s3"
│ 
│ The "backend" is the interface that Terraform uses to store state,
│ perform operations, etc. If this message is showing up, it means that the
│ Terraform configuration you're using is using a custom configuration for
│ the Terraform backend.
│ 
│ Changes to backend configurations require reinitialization. This allows
│ Terraform to set up the new configuration, copy existing state, etc. Please
│ run
│ "terraform init" with either the "-reconfigure" or "-migrate-state" flags
│ to
│ use the current configuration.
│ 
│ If the change reason above is incorrect, please verify your configuration
│ hasn't changed and try again. At this point, no changes to your existing
│ configuration or state have been made.
╵
Initializing the backend...

Successfully configured the backend "local"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing modules...
Downloading registry.terraform.io/terraform-aws-modules/security-group/aws 5.3.1 for db_security_group...
- db_security_group in /tmp/tmpsl1cop4q/modules/db_security_group
Downloading registry.terraform.io/terraform-aws-modules/rds/aws 6.13.1 for rds-master...
- rds-master in /tmp/tmpsl1cop4q/modules/rds-master
- rds-master.db_instance in /tmp/tmpsl1cop4q/modules/rds-master/modules/db_instance
- rds-master.db_instance_role_association in /tmp/tmpsl1cop4q/modules/rds-master/modules/db_instance_role_association
- rds-master.db_option_group in /tmp/tmpsl1cop4q/modules/rds-master/modules/db_option_group
- rds-master.db_parameter_group in /tmp/tmpsl1cop4q/modules/rds-master/modules/db_parameter_group
- rds-master.db_subnet_group in /tmp/tmpsl1cop4q/modules/rds-master/modules/db_subnet_group
Downloading registry.terraform.io/terraform-aws-modules/rds/aws 6.13.1 for rds-replica...
- rds-replica in /tmp/tmpsl1cop4q/modules/rds-replica
- rds-replica.db_instance in /tmp/tmpsl1cop4q/modules/rds-replica/modules/db_instance
- rds-replica.db_instance_role_association in /tmp/tmpsl1cop4q/modules/rds-replica/modules/db_instance_role_association
- rds-replica.db_option_group in /tmp/tmpsl1cop4q/modules/rds-replica/modules/db_option_group
- rds-replica.db_parameter_group in /tmp/tmpsl1cop4q/modules/rds-replica/modules/db_parameter_group
- rds-replica.db_subnet_group in /tmp/tmpsl1cop4q/modules/rds-replica/modules/db_subnet_group
Initializing provider plugins...
- Reusing previous version of hashicorp/helm from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of cyrilgdn/postgresql from the dependency lock file
- Reusing previous version of alekc/kubectl from the dependency lock file
- Installing hashicorp/helm v2.17.0...
- Installed hashicorp/helm v2.17.0 (signed by HashiCorp)
- Installing hashicorp/aws v6.36.0...
- Installed hashicorp/aws v6.36.0 (signed by HashiCorp)
- Installing hashicorp/random v3.8.1...
- Installed hashicorp/random v3.8.1 (signed by HashiCorp)
- Installing cyrilgdn/postgresql v1.22.0...
- Installed cyrilgdn/postgresql v1.22.0 (self-signed, key ID 3918DD444A3876A6)
- Installing alekc/kubectl v2.1.3...
- Installed alekc/kubectl v2.1.3 (self-signed, key ID 772FB27A86DAFCE7)
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://developer.hashicorp.com/terraform/cli/plugins/signing

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Generating Terragrunt Plan..

╷
│ Error: Backend initialization required: please run "terraform init"
│ 
│ Reason: Backend type changed from "local" to "s3"
│ 
│ The "backend" is the interface that Terraform uses to store state,
│ perform operations, etc. If this message is showing up, it means that the
│ Terraform configuration you're using is using a custom configuration for
│ the Terraform backend.
│ 
│ Changes to backend configurations require reinitialization. This allows
│ Terraform to set up the new configuration, copy existing state, etc. Please
│ run
│ "terraform init" with either the "-reconfigure" or "-migrate-state" flags
│ to
│ use the current configuration.
│ 
│ If the change reason above is incorrect, please verify your configuration
│ hasn't changed and try again. At this point, no changes to your existing
│ configuration or state have been made.
╵
╷
│ Error: Backend initialization required: please run "terraform init"
│ 
│ Reason: Backend type changed from "local" to "s3"
│ 
│ The "backend" is the interface that Terraform uses to store state,
│ perform operations, etc. If this message is showing up, it means that the
│ Terraform configuration you're using is using a custom configuration for
│ the Terraform backend.
│ 
│ Changes to backend configurations require reinitialization. This allows
│ Terraform to set up the new configuration, copy existing state, etc. Please
│ run
│ "terraform init" with either the "-reconfigure" or "-migrate-state" flags
│ to
│ use the current configuration.
│ 
│ If the change reason above is incorrect, please verify your configuration
│ hasn't changed and try again. At this point, no changes to your existing
│ configuration or state have been made.
╵
Traceback (most recent call last):
  File "/home/user/devel/infrastructure/live/.venv/bin/terravision", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/devel/infrastructure/live/.venv/lib/python3.11/site-packages/terravision/terravision.py", line 652, in main
    cli(
  File "/home/user/devel/infrastructure/live/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/devel/infrastructure/live/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/devel/infrastructure/live/.venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/devel/infrastructure/live/.venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/devel/infrastructure/live/.venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/devel/infrastructure/live/.venv/lib/python3.11/site-packages/terravision/terravision.py", line 382, in draw
    tfdata = compile_tfdata(
             ^^^^^^^^^^^^^^^
  File "/home/user/devel/infrastructure/live/.venv/lib/python3.11/site-packages/terravision/terravision.py", line 193, in compile_tfdata
    tfdata = tgwrapper.tg_initplan(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/devel/infrastructure/live/.venv/lib/python3.11/site-packages/modules/tgwrapper.py", line 436, in tg_initplan
    _run_terragrunt_plan(codepath, varfile, tfplan_path, debug)
  File "/home/user/devel/infrastructure/live/.venv/lib/python3.11/site-packages/modules/tgwrapper.py", line 358, in _run_terragrunt_plan
    raise RuntimeError(f"Terragrunt plan failed:\n{stderr}{hint}")
RuntimeError: Terragrunt plan failed:
```

If I run the terravision comand again the output is the same.

I also noticed that I have activated provider caching but I thiiiiink terravision is always downloading them

```
$ env | grep CACHE
TG_PROVIDER_CACHE=1
TERRAGRUNT_PROVIDER_CACHE=1
TG_PROVIDER_CACHE_DIR=/home/user/.terragrunt_provider_cache
TERRAGRUNT_PROVIDER_CACHE_DIR=/home/user/.terragrunt_provider_cache
```

**Comment by robinbowes** [comment]
@patrickchugh I tried again with the latest version (0.32.0) and I now see init and plan executed for all three clouds.

However, I get this backtrace before the graph is shown:

```
Traceback (most recent call last):
  File "/Users/robin/.local/bin/terravision", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/robin/.local/share/uv/tools/terravision/lib/python3.12/site-packages/terravision/terravision.py", line 652, in main
    cli(
  File "/Users/robin/.local/share/uv/tools/terravision/lib/python3.12/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robin/.local/share/uv/tools/terravision/lib/python3.12/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/robin/.local/share/uv/tools/terravision/lib/python3.12/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robin/.local/share/uv/tools/terravision/lib/python3.12/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robin/.local/share/uv/tools/terravision/lib/python3.12/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robin/.local/share/uv/tools/terravision/lib/python3.12/site-packages/terravision/terravision.py", line 382, in draw
    tfdata = compile_tfdata(
             ^^^^^^^^^^^^^^^
  File "/Users/robin/.local/share/uv/tools/terravision/lib/python3.12/site-packages/terravision/terravision.py", line 245, in compile_tfdata
    tfdata = _enrich_graph_data(tfdata, debug, already_processed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robin/.local/share/uv/tools/terravision/lib/python3.12/site-packages/terravision/terravision.py", line 106, in _enrich_graph_data
    tfdata = interpreter.resolve_all_variables(tfdata, debug, already_processed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robin/.local/share/uv/tools/terravision/lib/python3.12/site-packages/modules/interpreter.py", line 46, in resolve_all_variables
    tfdata = inject_module_variables(tfdata)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robin/.local/share/uv/tools/terravision/lib/python3.12/site-packages/modules/interpreter.py", line 113, in inject_module_variables
    value = handle_module_vars(str(value), tfdata)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robin/.local/share/uv/tools/terravision/lib/python3.12/site-packages/modules/interpreter.py", line 91, in handle_module_vars
    eval_string = helpers.cleanup_curlies(eval_string.replace(modulevar, outvalue))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: replace() argument 2 must be str, not dict
```

I have a tfdata.json - I can't share it, but I'm happy to issue any debug commands that might help figure out what the problem is.

**Comment by patrickchugh** [comment]
@lgg42 New release out with --debug improvements and targeted Terragrunt diagnostics aimed at your "backend keeps changing" symptom.

I've tried hard to reproduce locally — terragrunt 0.94.0, real S3 backend, your exact dependency + generate "backend" pattern, with TG_PROVIDER_CACHE set — and can't trigger it. Something specific to your env is in play.

Could you upgrade and re-run `terravision draw --debug --source .`?

The new diagnostic prints --- [tg-debug] --- sections at four checkpoints (after init, after fallback init, before plan, after plan). Each shows whether terravision_override.tf exists, what backend backend.tf declares, what terraform's stored state claims, and every .tf-containing dir under .terragrunt-cache/. Paste those sections (sanitized) and we should be able to pinpoint exactly when things go wrong.

Also helpful:

1. Sanitized root.hcl generate "backend" block and rds/terragrunt.hcl
2. Whether running terragrunt directly with terravision's exact args fails the same way:
```
cd <rds dir>
TF_CLI_ARGS_init=-reconfigure TF_INPUT=false terragrunt init -reconfigure
TF_CLI_ARGS_init=-reconfigure TF_INPUT=false terragrunt plan -refresh=false -out=/tmp/tg-plan.bin
```
If that fails standalone → terragrunt/config bug. If it succeeds but terravision still fails → terravision is doing something extra.

3. Sanity check: try unset TG_PROVIDER_CACHE TERRAGRUNT_PROVIDER_CACHE TG_PROVIDER_CACHE_DIR TERRAGRUNT_PROVIDER_CACHE_DIR before running terravision. If the bug goes away, the provider cache is involved.

Thanks for sticking with this.

**Comment by patrickchugh** [comment]
@robinbowes Can you try again with the latest code? That was a bug unrealted to terragrunt and it should be fixed

**Comment by lgg42** [comment]
> [@lgg42](https://github.com/lgg42) New release out with --debug improvements and targeted Terragrunt diagnostics aimed at your "backend keeps changing" symptom.
> 
> I've tried hard to reproduce locally — terragrunt 0.94.0, real S3 backend, your exact dependency + generate "backend" pattern, with TG_PROVIDER_CACHE set — and can't trigger it. Something specific to your env is in play.
> 
> Could you upgrade and re-run `terravision draw --debug --source .`?
> 
> The new diagnostic prints --- [tg-debug] --- sections at four checkpoints (after init, after fallback init, before plan, after plan). Each shows whether terravision_override.tf exists, what backend backend.tf declares, what terraform's stored state claims, and every .tf-containing dir under .terragrunt-cache/. Paste those sections (sanitized) and we should be able to pinpoint exactly when things go wrong.
> 
> Also helpful:
> 
> 1. Sanitized root.hcl generate "backend" block and rds/terragrunt.hcl
> 2. Whether running terragrunt directly with terravision's exact args fails the same way:
> 
> ```
> cd <rds dir>
> TF_CLI_ARGS_init=-reconfigure TF_INPUT=false terragrunt init -reconfigure
> TF_CLI_ARGS_init=-reconfigure TF_INPUT=false terragrunt plan -refresh=false -out=/tmp/tg-plan.bin
> ```
> 
> If that fails standalone → terragrunt/config bug. If it succeeds but terravision still fails → terravision is doing something extra.
> 
> 3. Sanity check: try unset TG_PROVIDER_CACHE TERRAGRUNT_PROVIDER_CACHE TG_PROVIDER_CACHE_DIR TERRAGRUNT_PROVIDER_CACHE_DIR before running terravision. If the bug goes away, the provider cache is involved.
> 
> Thanks for sticking with this.

Hey! Thanks! I need to dedicate some time to execute these steps carefully and provide you with the info you request. In the meanwhile, here's the new output with the new terravision version 0.33.0 (the rest of the error is the same as before)

```
[tg-debug] _find_terragrunt_cache_dir candidates (2):
  SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg: marker=backend.tf terragrunt_sig_in_first_200B=True
  SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg: marker=provider.tf terragrunt_sig_in_first_200B=True
[tg-debug] picked: SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg

--- [tg-debug] after terragrunt init ---
  cache_dir: /home/luis/devel/infrastructure/live/staging/us-east-1/data-stores/rds/shared/.terragrunt-cache/SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg
  TF_DATA_DIR: /tmp/tmpt3uydbm6
  override file: MISSING
  backend.tf: EXISTS (325 bytes)
    backend type in file: s3
  stored state (TF_DATA_DIR): MISSING (/tmp/tmpt3uydbm6/terraform.tfstate)
  stored .terraform/terraform.tfstate (cache_dir): backend.type='s3'
  .tf files in cache_dir: ['backend.tf', 'main.tf', 'outputs.tf', 'provider.tf', 'variables.tf', 'versions.tf']
  all .tf-containing dirs in .terragrunt-cache (2 found):
    SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg [PICKED]: markers=['backend.tf', 'provider.tf'] has_local_state=True
    SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg/examples/complete: markers=[] has_local_state=False
```
---
```
--- [tg-debug] after fallback terraform init ---
  cache_dir: /home/luis/devel/infrastructure/live/staging/us-east-1/data-stores/rds/shared/.terragrunt-cache/SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg
  TF_DATA_DIR: /tmp/tmpt3uydbm6
  override file: EXISTS (39 bytes)
    content: 'terraform {\n  backend "local" {\n\n  }\n}\n'
  backend.tf: EXISTS (325 bytes)
    backend type in file: s3
  stored .terraform/terraform.tfstate (TF_DATA_DIR): backend.type='local'
  stored .terraform/terraform.tfstate (cache_dir): backend.type='s3'
  .tf files in cache_dir: ['backend.tf', 'main.tf', 'outputs.tf', 'provider.tf', 'terravision_override.tf', 'variables.tf', 'versions.tf']
  all .tf-containing dirs in .terragrunt-cache (2 found):
    SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg [PICKED]: markers=['backend.tf', 'provider.tf', 'terravision_override.tf'] has_local_state=True
    SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg/examples/complete: markers=[] has_local_state=False

--- [tg-debug] before terragrunt plan ---
  cache_dir: /home/luis/devel/infrastructure/live/staging/us-east-1/data-stores/rds/shared/.terragrunt-cache/SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg
  TF_DATA_DIR: /tmp/tmpt3uydbm6
  override file: EXISTS (39 bytes)
    content: 'terraform {\n  backend "local" {\n\n  }\n}\n'
  backend.tf: EXISTS (325 bytes)
    backend type in file: s3
  stored .terraform/terraform.tfstate (TF_DATA_DIR): backend.type='local'
  stored .terraform/terraform.tfstate (cache_dir): backend.type='s3'
  .tf files in cache_dir: ['backend.tf', 'main.tf', 'outputs.tf', 'provider.tf', 'terravision_override.tf', 'variables.tf', 'versions.tf']
  all .tf-containing dirs in .terragrunt-cache (2 found):
    SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg [PICKED]: markers=['backend.tf', 'provider.tf', 'terravision_override.tf'] has_local_state=True
    SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg/examples/complete: markers=[] has_local_state=False
```
---

```
--- [tg-debug] after terragrunt plan ---
  cache_dir: /home/luis/devel/infrastructure/live/staging/us-east-1/data-stores/rds/shared/.terragrunt-cache/SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg
  TF_DATA_DIR: /tmp/tmpt3uydbm6
  override file: EXISTS (39 bytes)
    content: 'terraform {\n  backend "local" {\n\n  }\n}\n'
  backend.tf: EXISTS (325 bytes)
    backend type in file: s3
  stored .terraform/terraform.tfstate (TF_DATA_DIR): backend.type='local'
  stored .terraform/terraform.tfstate (cache_dir): backend.type='s3'
  .tf files in cache_dir: ['backend.tf', 'main.tf', 'outputs.tf', 'provider.tf', 'terravision_override.tf', 'variables.tf', 'versions.tf']
  all .tf-containing dirs in .terragrunt-cache (2 found):
    SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg [PICKED]: markers=['backend.tf', 'provider.tf', 'terravision_override.tf'] has_local_state=True
    SDfN2i3sTq0VOYvEujwmY4M7xRo/jqFGG9H7GHjRW01WwSdma-8YcIg/examples/complete: markers=[] has_local_state=False

```

**Comment by patrickchugh** [comment]
@lgg42 We implemented a fix. Can you try with the latest version? I still cannot reproduce your problem locally so if it still doesn't work just share the debug output again. Thanks.

**Comment by robinbowes** [comment]
> [@robinbowes](https://github.com/robinbowes) Can you try again with the latest code? That was a bug unrealted to terragrunt and it should be fixed

Hi @patrickchugh,

I still see the same error:

```
ERROR: replace() argument 2 must be str, not dict
```

I also see lots of warnings:
```
WARNING: Cannot resolve variable after 50 iterations: toset(keys(module.security_groups.security_groups))
```
and:
```
WARNING: Cannot resolve variable after 50 iterations: module.security_groups.security_group_entries
```

Both warnings show for various variables and resources, not just the two listed above.

**Comment by patrickchugh** [comment]
@robinbowes Can you produce a diagram in the end? If so, can you please run terravision with the --debug flag, and then share your tfdata.json dump file so I can try to re-produce the error? You can do a find/replace on the JSON to replace any account numbers or other data you wish to mask before sharing.


> > [@robinbowes](https://github.com/robinbowes) Can you try again with the latest code? That was a bug unrealted to terragrunt and it should be fixed
> 
> Hi [@patrickchugh](https://github.com/patrickchugh),
> 
> I still see the same error:
> 
> ```
> ERROR: replace() argument 2 must be str, not dict
> ```
>  
> ```
> WARNING: Cannot resolve variable after 50 iterations: module.security_groups.security_group_entries
> ```
>

**Comment by lgg42** [comment]
> [@lgg42](https://github.com/lgg42) We implemented a fix. Can you try with the latest version? I still cannot reproduce your problem locally so if it still doesn't work just share the debug output again. Thanks.

For the rds/shared unit it shows the same error, but I tried a different unit and it worked and generated the diagram. I've tried another single-module and multi-modules and it fails in some of them and succeed in other
